db:
  image: mongo
  volumes:
    - /media/rocketchat/data/db:/data/db
    - /media/rocketchat/data/dump:/dump
  command: mongod --smallfiles
  ports:
    - 27017:27017

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chatter.mydomain.com
  links:
    - db:db
  ports:
    - 3000:3000