elasticsearch:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
  environment:
    - ES_HEAP_SIZE=1g
  volumes:
    - /usr/local/dc_elk-kibana/config:/usr/share/elasticsearch/config
  cap_add:
    - IPC_LOCK
  ulimits:
    memlock:
      soft: -1
      hard: -1
kibana:
  image: kibana
  ports:
    - 5601:5601
    - 80:5601
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch