version: '2'
services:
  db:
    image: mongo
    volumes:
      - /media/rocketchat/data/db:/data/db
      - /media/rocketchat/data/dump:/dump
    command: mongod --smallfiles
    ports:
      - 27017:27017
    restart: always

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=https://localhost:443/
    links:
      - db:db
    ports:
      - 3000:3000
    restart: always
    depends_on:
        - db