version: '2'
services:
  db:
    image: mariadb
    volumes:
      - "./.database:/var/lib/mysql"
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    #working_dir: /var/www/html
    volumes:
      - ~/wordpress/wp_html:/var/www/html
      - ~/wordpress/wp_html/wp-content:/var/www/html/wp-content:rw
      #- uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
      - db:mysql
    ports:
      - "8080:80"
    #restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - db:mysql
    ports:
      - 8181:80
    #restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: wordpress